name: Build and Deploy Next.js App to Docker Hub

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Adjust if needed

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      # Optional: Run tests
      # - name: Run tests
      #   run: npm test

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/canvas-ui:latest

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "✅ Successfully connected to VPS!"
            docker stop canvas-ui || true
            docker rm canvas-ui || true
            docker image prune -a -f
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/canvas-ui:latest
            docker run -d --name canvas-ui \
              --network canvas-app \
              -p 3000:3000 --restart always \
              -e NODE_ENV=production \
              ${{ secrets.DOCKERHUB_USERNAME }}/canvas-ui:latest
            docker system prune -f
